# Generated by Django 4.1.4 on 2022-12-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_company_employee_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_lead',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='first_app.employee'),
            preserve_default=False,
        ),
    ]
